name: Profile Summary Cards
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate
    steps:
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        with:
          USERNAME: algojogacor
          UTC_OFFSET: 7
          EXCLUDE: ""
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: "output"
          AUTO_INIT: true